### ISSUE TITLE
CreateAccountServlet

### ISSUE THREAD

**Issue by FarhanSharif** [shaizamzaheer/grocery-advisor#12]
A servlet that handles the create account process (LoginServlet can be used as a guide)

- takes info from create account form on login page
- checks database if user exists
- if doesnt exist
   - insert user into database
   - redirect to welcome page
- if exists
   - redirect to login page

**Comment by shaizamzaheer** [comment]
if exists they can just login.

**Comment by FarhanSharif** [comment]
Sure, I guess it depends on how we're going to do it? If the user enters correct username and password into create account fields, then that would be a sneaky way to log in. But if they enter an existing username and not the correct password, what's the reason for letting them in?
